;(function () {

    'use strict';

    angular.module('model.banks', [])
        .service('banks', banks);


    banks.$inject = ['http', 'url'];

    function banks(http, url) {


        let service = {
            getAllBanks: getAllBanks,
        };
        return service;

        function getAllBanks() {
            return ["Abrechnungsbank",
                "Allianz",
                "Alte Leipziger Bauspar",
                "BBBank",
                "BBVA",
                "BHW Auslandsfinanzierung ",
                "BHW Bausparkasse ",
                "BKM",
                "BSK Schwäbisch Hall ",
                "BW Bank BankaMarch ",
                "Bankverein Werther ",
                "Barmenia ",
                "BauFi Direkt-Bank ",
                "BaufinanzTeam Bank ",
                "Berliner Sparkasse ",
                "Berliner Volksbank ",
                "BordesholmerSpk",
                "Braunschweigische Landessparkasse",
                "Bremische Volksbank ",
                "CaixaBank ",
                "CoBa Darmstadt ",
                "Commerzbank ",
                "DB Indiv. Berlin ",
                "DB Indiv. Frankfurt ",
                "DB Indiv. Hamburg ",
                "DB Indiv. Lübeck ",
                "DB Indiv. München ",
                "DB Individuell Köln ",
                "DEVK ",
                "DKB",
                "DSL Bank",
                "Degussa Bank",
                "Deutsche Bank",
                "Deutsche Bank SA Espanola",
                "Deutscher Ring Bausparkasse",
                "ERGO",
                "Erfurter Bank",
                "Erzgebirgssparkasse ",
                "Frankenberger Bank ",
                "Förde Sparkasse ",
                "GENO BANK ESSEN ",
                "Generali",
                "Gladbacher Bank AG ",
                "GladbacherBankN ",
                "Hamburger Sparkasse ",
                "Hamburger Volksbank ",
                "Hannoversche Leben ",
                "Hannoversche Volksbank ",
                "HanseaticBank ",
                "Harzsparkasse ",
                "Hausbank München ",
                "HeidenheimerVoBa ",
                "Herner Sparkasse ",
                "HypoVereinsbank ",
                "IB.SH",
                "ING-DiBa ",
                "INTERCAPITAL ",
                "Ihre Bank",
                "KSK Anhalt-Bitterfeld ",
                "KSK Augsburg ",
                "KSK Bautzen ",
                "KSK Böblingen ",
                "KSK Börde ",
                "KSK Döbeln",
                "KSK Esslingen-Nürtingen ",
                "KSK Euskirchen ",
                "KSK Freudenstadt ",
                "KSK Groß-Gerau ",
                "KSK Heilbronn ",
                "KSK Heinsberg ",
                "KSK Herzogtum Lauenburg ",
                "KSK Köln",
                "KSK Limburg\t",
                "KSK Ludwigsburg ",
                "KSK Mayen",
                "KSK München-Starnberg ",
                "Ebersberg ",
                "KSK Nordhausen ",
                "KSK Osterholz ",
                "KSK Peine",
                "KSK Saalfeld-Rudolstadt ",
                "KSK Stendal ",
                "KSK Syke ",
                "KSK Tuttlingen ",
                "KSK Waiblingen ",
                "KSK Walsrode ",
                "Kasseler Bank ",
                "Kasseler Spk ",
                "Kyffhäusersparkasse ",
                "Kölner Bank ",
                "LBS Nord ",
                "LBS Ost",
                "LBS SHH ",
                "LBS Südwest ",
                "LBS West",
                "Landessparkasse zu Oldenburg",
                "Liga Bank",
                "MHB",
                "Mainzer Volksbank ",
                "Meine WB",
                "Mittelbrandenburgische Sparkasse",
                "Muster-Sparkasse",
                "Musterbank",
                "Münchener Verein",
                "Münchner Bank",
                "Müritz-Sparkasse",
                "Naspa",
                "Nord-Ostsee Sparkasse ",
                "Nordthüringer VoBa",
                "NÄV",
                "Ostfriesische Volksbank ",
                "OstseeSparkasse Rostock ",
                "Ostsächsische Sparkasse Dresden ",
                "PAX-Bank ",
                "PENKA",
                "PSD Berlin Brandenburg ",
                "PSD Braunschweig ",
                "PSD Hannover ",
                "PSD Hessen-Thüringen ",
                "PSD Kiel ",
                "PSD Koblenz ",
                "PSD Köln ",
                "PSD München",
                "PSD Niederbayern-Oberpfalz ",
                "PSD Nord ",
                "PSD Nürnberg ",
                "PSD Rhein-Ruhr ",
                "PSD RheinNeckarSaar",
                "PSD Testbank",
                "PSD Westfalen-Lippe",
                "Pommersche Volksbank",
                "Provinzial NW",
                "Provinzial Rheinland",
                "R+V Lebensversicherung AG",
                "RaiBa Bad Bramstedt",
                "RaiBa Baunatal",
                "RaiBa Griesstätt - Haifing eG",
                "RaiBa Kirchheim-Walheim",
                "RaiBa Kraichgau",
                "RaiBa Lauenburg",
                "RaiBa RIES",
                "RaiBa Ratzeburg",
                "RaiBa Ried",
                "Raiba Bargteheide",
                "Raiba Gräfenberg - Forchheim - Eschenau - Heroldsberg ",
                "Raiba Plankstetten",
                "RaiBa Ried",
                "Raiba Ravensburg",
                "Raiffeisenbank Geiselhöring-Pfaffenberg ",
                "Rhön-Rennsteig Sparkasse ",
                "Rüsselsheimer Volksbank ",
                "SKB Rheinstetten ",
                "SKG",
                "SSK Augsburg ",
                "SSK Dessau ",
                "SSK Düsseldorf ",
                "SSK Lengerich ",
                "SSK Magdeburg ",
                "SSK München ",
                "SSK Remscheid ",
                "SSK Wedel ",
                "SSK Wuppertal",
                "Saalesparkasse\t",
                "Sabadell",
                "Salzlandsparkasse",
                "Santander",
                "Santander - externe Vertriebe ",
                "Santander Central Hispano ",
                "Signal Iduna",
                "Sparda Baden-Württemberg ",
                "Sparda Berlin ",
                "Sparda Hamburg ",
                "Sparda Hannover ",
                "Sparda München ",
                "Sparda Münster ",
                "Sparda Nürnberg ",
                "Sparda Südwest ",
                "Sparda West",
                "Sparkasse Ostprignitz-Ruppin ",
                "Spk Minden-Lübbecke ",
                "Spk Aachen ",
                "Spk Altenburger Land ",
                "Spk Altmark West ",
                "Spk Bad Kissingen ",
                "Spk Barnim ",
                "Spk Bayreuth ",
                "Spk Bielefeld ",
                "SpkBodensee ",
                "Spk Bremen ",
                "Spk Burgenlandkreis ",
                "Spk Celle ",
                "Spk Chemnitz ",
                "Spk Deggendorf ",
                "Spk Dillenburg ",
                "Spk Dillingen ",
                "Spk Donnersberg ",
                "Spk Duisburg ",
                "Spk Düren ",
                "Spk Elbe-Elster",
                "Spk Elmshorn",
                "Spk Emsland",
                "Spk Essen",
                "Spk Frankfurt",
                "Spk Fürstenfeldbruck",
                "Spk Fürth",
                "Spk Gera-Greiz",
                "Spk Gießen",
                "Spk Gifhorn-Wolfsburg",
                "Spk Gütersloh",
                "Spk HagenHerdecke",
                "Spk Hanau",
                "Spk Hannover",
                "Spk Harburg-Buxtehude",
                "Spk Hegau-Bodensee",
                "Spk Hilden-Ratingen-Velbert",
                "Spk Hildesheim Goslar Peine",
                "Spk Hochfranken",
                "Spk Holstein",
                "Spk Höxter \t",
                "Spk Karlsruhe ",
                "Spk Krefeld",
                "Spk Kulmbach-Kronach",
                "Spk Köln Bonn",
                "Spk Landsberg-Dießen",
                "Spk Landshut",
                "Spk Langen-Seligenstadt",
                "Spk LeerWittmund",
                "Spk Leipzig",
                "Spk Leverkusen",
                "Spk Lübeck",
                "Spk Lüneburg",
                "Spk Mainfranken-Würzburg",
                "Spk Mansfeld-Südharz",
                "Spk Mecklenburg-Nordwest",
                "Spk Mecklenburg-Schwerin",
                "Spk Mecklenburg-Strelitz",
                "Spk Meißen\t",
                "Spk Miltenberg-Obernburg",
                "Spk Mittelholstein",
                "Spk Mittelsachsen",
                "Spk Mittelthüringen",
                "Spk Muldental",
                "Spk Märkisch-Oderland",
                "Spk Mülheim an der Ruhr",
                "Spk Neubrandenburg-Demmin",
                "Spk Neumarkt-Parsberg",
                "Spk Neuss",
                "Spk Nienburg",
                "Spk Nürnberg",
                "Spk Oberhessen",
                "Spk Oberlausitz-Niederschlesien",
                "Spk Oder-Spree",
                "Spk Osnabrück",
                "Spk Paderborn-Detmold",
                "Spk Parchim-Lübz\t",
                "Spk Passau ",
                "Spk Pforzheim-Calw ",
                "Spk Rhein-Maas ",
                "Spk Rhein-Neckar-Nord ",
                "Spk Rottal-Inn ",
                "Spk Schaumburg ",
                "Spk Schwarzwald-Baar ",
                "Spk Siegen ",
                "Spk Soest",
                "Spk Stade-Altes Land ",
                "Spk Südholstein ",
                "Spk Uckermark ",
                "Spk Uecker-Randow ",
                "Spk Ulm",
                "Spk Vest-Recklinghausen ",
                "Spk Vogtland ",
                "Spk Vorpommern ",
                "Spk Werra-Meißner",
                "Spk Wittenberg ",
                "Spk Zwickau ",
                "Steyler Bank ",
                "Swiss Life ",
                "Südwestbank ",
                "VB Bad Oeynhausen ",
                "VB Bielefeld-Güters.",
                "VB Düsseldorf R ",
                "VB Hildesheim ",
                "VB Lauterbach-Schl ",
                "VB Trier",
                "VR Bad Hersfeld-Rotenburg ",
                "VR Bamberg ",
                "VR Bank Fulda ",
                "VR Bank Greifswald ",
                "VR Bank Main-Kinzig ",
                "VR Bank Meißen Großenhain",
                "VR Bank München Land",
                "VR Bank Niebüll",
                "VR Bank NordRhön",
                "VR Bank Nordeifel",
                "VR Bank Nürnberg",
                "VR Bank Ostholstein Nord - Plön",
                "VR Bank Rhein-Erft",
                "VR Bank Rhein-Neckar",
                "VR Bank Starnberg-Herrsching-Landsberg",
                "VR Bank Steinlach-Wiesaz-Härten",
                "VR Bank Untertaunus",
                "VR Bank Westmünsterland",
                "VR Bank Westthüringen",
                "VR Dachau",
                "VR Donau-Mindel",
                "VR Dresden",
                "VR Erlangen",
                "VR Flensburg-Schles.",
                "VR Hessenland",
                "VR Mittelfranken ",
                "VR Mittelsachsen ",
                "VR Rhön-Grabfeld ",
                "VR Rosenheim-Chiemsee ",
                "VR Schweinfurt ",
                "VR Torgau ",
                "VR Waldecker Bank ",
                "VR Werra-Meißner ",
                "VR Würzburg ",
                "VR im Enzkreis ",
                "VR-Bank Memmingen eG ",
                "VR-Bank Rottal-Inn ",
                "VR-Musterbank",
                "VRB Schwäbisch Hall Crailsheim ",
                "WB Böblingen ",
                "WRB Reinheim ",
                "VZN",
                "Vereinigte Volksbank Münster ",
                "Vereinigte Volksbank Münster M",
                "Vereinigte Volksbank Münster N",
                "Vereinigte Volksbank Münster W",
                "VoBa Ahlen-Sassenberg-Warendorf",
                "VoBa Baden Baden Rastatt",
                "VoBa Bautzen",
                "VoBa Beckum-Lippstadt",
                "VoBa Bigge-Lenne",
                "VoBa Bocholt",
                "VoBa Bochum-Witten",
                "VoBa Bonn Rhein-Sieg",
                "VoBa Braunschweig Wolfsburg",
                "VoBa Breisgau Nord",
                "VoBa Breisgau Süd",
                "VoBa Bremen-Nord",
                "VoBa Bremerhaven-Cuxland",
                "VoBa Bruchsal Bretten",
                "VoBa Bruhrain-Kraich-Hardt",
                "VoBa Börde-Bernburg",
                "VoBa Darmstadt Südhessen",
                "VoBa Delmenhorst-Schierbrok ",
                "VoBa Dill",
                "VoBa Donau-Neckar",
                "VoBa Dortmund Nordwest",
                "VoBa Düsseldorf N",
                "VoBa Düsseldorf Neuss",
                "VoBa Düsseldorf Neuss W",
                "VoBa Elsen-Wewer-Borchen",
                "VoBa Esslingen",
                "VoBa Fürstenfeldbruck",
                "VoBa Greven",
                "VoBa Gronau-Ahaus",
                "VoBa Göppingen",
                "VoBa Hameln-Stadthagen",
                "VoBa Herrenberg-Nagold-Rottenburg",
                "VoBa Kaiserslautern",
                "VoBa Karlsruhe",
                "VoBa Kleverland",
                "VoBa Konstanz",
                "VoBa Kraichgau ",
                "VoBa Krefeld ",
                "VoBa Lahr",
                "VoBa Laupheim-Illertal ",
                "VoBa Lübeck ",
                "VoBa Lüneburger Heide ",
                "VoBa Mainspitze ",
                "VoBa Merz ",
                "VoBa Mittelhessen ",
                "VoBa Mittweida ",
                "VoBa Mittweida M ",
                "VoBa Mittweida W ",
                "VoBa Mosbach ",
                "VoBa Märkischer Kreis ",
                "VoBa Müllheim ",
                "VoBa Nordschwarzwald ",
                "VoBa Oberberg",
                "VoBa Paderborn-Höxter-Detmold ",
                "VoBa Pforzheim",
                "VoBa Pirna",
                "VoBa Remscheid-Solingen",
                "VoBa Rhein-Lippe",
                "VoBa Rhein-Ruhr",
                "VoBa Rhein-Wehra",
                "VoBa Rhein-Wupper",
                "VoBa RheinAhrEifel",
                "VoBa Riesa",
                "VoBa Ruhr-Mitte",
                "VoBa Sauerland",
                "VoBa Schwarzwald Baar Hegau",
                "VoBa Seesen",
                "VoBa Siegerland",
                "VoBa Stade-Cuxhaven",
                "VoBa Stendal",
                "VoBa Stuttgart",
                "VoBa Ulm-Biberach",
                "VoBa Vogtland",
                "VoBa Weschnitztal regional",
                "VoBa Wolfenbüttel",
                "VoBa im Harz",
                "VoBa im Unterland",
                "VoBa in Schaumburg",
                "VoBa in der Ortenau (Offenburg)",
                "Volksbank Neckartal eG",
                "Volkswohl Bund",
                "WL BANK",
                "Weser-Elbe Sparkasse",
                "Westerwald Bank",
                "Wiesbadener VoBa",
                "Württembergische",
                "Wüstenrot Bausparkasse",
                "Zeit+Gewinn-Bank",
                "apobank",
                "r/d/s-Bank",
                "uniVersa",
                "von Essen Bank",
                "Sonstiger Darlehensgeber"];
        }
    }
})();

